### ISSUE TITLE
java.lang.RuntimeException: Failed to load Hive builtin functions

### ISSUE THREAD

**Issue by jijomathew35** [Cascading/cascading-hive#13]
I am running HiveDemo.java 
I have hive-builtins jar in my build.
I am getting exception:-
flow failed: load data into dual
java.lang.RuntimeException: Failed to load Hive builtin functions
        at org.apache.hadoop.hive.ql.session.SessionState.<init>(SessionState.java:217)
        at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:265)
        at cascading.flow.hive.HiveDriverFactory.createHiveDriver(HiveDriverFactory.java:67)
        at cascading.flow.hive.HiveQueryRunner.run(HiveQueryRunner.java:77)
        at cascading.flow.hive.HiveRiffle.complete(HiveRiffle.java:97)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at riffle.process.scheduler.ProcessWrapper.invokeMethod(ProcessWrapper.java:178)
        at riffle.process.scheduler.ProcessWrapper.findInvoke(ProcessWrapper.java:166)
        at riffle.process.scheduler.ProcessWrapper.complete(ProcessWrapper.java:147)
        at cascading.flow.hadoop.ProcessFlow.complete(ProcessFlow.java:199)
        at cascading.flow.hive.HiveFlow.complete(HiveFlow.java:145)
        at cascading.cascade.Cascade$CascadeJob.call(Cascade.java:1057)
        at cascading.cascade.Cascade$CascadeJob.call(Cascade.java:1005)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.FileNotFoundException: /tmp/hadoop-stark/hadoop-unjar4751041980891901498 (Is a directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
        at java.util.zip.ZipFile.<init>(ZipFile.java:145)
        at java.util.jar.JarFile.<init>(JarFile.java:153)
        at java.util.jar.JarFile.<init>(JarFile.java:90)
        at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
        at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
        at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
        at java.net.URL.openStream(URL.java:1037)
        at org.apache.hadoop.hive.ql.exec.FunctionRegistry.registerFunctionsFromPluginJar(FunctionRegistry.java:1307)
        at org.apache.hadoop.hive.ql.session.SessionState.<init>(SessionState.java:213)
        ... 19 more

**Comment by jijomathew35** [comment]
Sorry to ask this over here.
I will try to get a solution from the forum.

**Comment by fs111** [comment]
It is fine to report problems here. Could you explain your environment a little bit? Which version of hadoop and hive are you using?

**Comment by jijomathew35** [comment]
Hadoop version:- 2.0.0-cdh4.5.0
Hive version:-0.10.0-cdh4.5.0 

I am trying to create the table dual within a db "dbtest".
The table is getting created but the loading is failing.

this is the command i have given:-
load data local inpath '/home/stark/Workspace_all/TestDir/dot/data.txt' overwrite into table dbtest.dual.

I have mentioned the table name in hiveTableDescriptor.

I have full privileges to the database and am able to run "load data local in path" command from the hive console.

**Comment by fs111** [comment]
When using old versions of hive like 0.10, you have to add a few more dependencies by hand. You will have to add the hive-builtins jar as well. Later versions don't need that.

**Comment by fs111** [comment]
Closing, if this is still an issue, please re-open it.
