### ISSUE TITLE
cascading-hive:Table not Stored in Metastore DB

### ISSUE THREAD

**Issue by Nevil-DSOUZA** [Cascading/cascading-hive#18]
The table we created from the code are not store in <b> metastore db</b>.
It create a table in  HDFS.But it not showing in <b> Hive Shell</b> when we do <b>show tables;</b>

This is the HiveTableDescriptor code: 

<p>HiveTableDescriptor sinkTableDescriptor = new HiveTableDescriptor( "CallCenterDB", "transdata_result", CALL_CENTER_TABLE_FIELDS, CALL_CENTER_TABLE_TYPES );</p>

Please solve this issue.

**Comment by fs111** [comment]
Did you configure a remote metastore in your configuration?

You have to have something like this in your config to make it work properly:

```
<property>
    <name>hive.metastore.uris</name>
    <value>thrift://<hostname>:9083</value>
 </property>
```

**Comment by Nevil-DSOUZA** [comment]
```
I set configure in hive-site.xml  in server machine But it still giving same exception
<property>
   <name>hive.metastore.uris</name>
    <value>thrift://hdmaster:9083</value>
 </property>
```

**Comment by fs111** [comment]
You have to have that in your config on the client as well, since the
client and also the remote jvms talk to the metastore.
- André

On Fri, Jun 19, 2015 at 3:54 AM, Nevil-DSOUZA notifications@github.com
wrote:

> I set configure in hive-site.xml  in server machine But it still giving same exception
> <property>
>    <name>hive.metastore.uris</name>
>     <value>thrift://hdmaster:9083</value>
>  </property>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cascading/cascading-hive/issues/18#issuecomment-113471204
> .

## 

André Kelpe
andre@concurrentinc.com
http://concurrentinc.com

**Comment by Nevil-DSOUZA** [comment]
We also tried set the configuration in client machine  but it still  not showing tables in Hive shell when we do <b>Show Tables</b>.If we create a table through hive table It storing in same HDFS location but when we do <b>show tables</b>.It only showing the table which we created through <b>hive shell</b>.

**Comment by fs111** [comment]
Can you share your configuration entries cluster side and client side with me? It works for many other uses just fine, so I suspect there is a mismatch somewhere.

BTW: Which version of Cascading-Hive are you using?

**Comment by ghost** [comment]
I am running into something similar when running a hive query to create an external table. I am using the latest version of cascading-hive (2.0.1-wip-13). My code is shown below:

``` java
HiveTableDescriptor hiveTableDescriptor = new HiveTableDescriptor(
    "devl_fraud",
    "test_table",
    new String[]{"b", "c", "a"},
    new String[]{"string", "string", "string"},
    new String[]{},
    ",",
    HiveTableDescriptor.HIVE_DEFAULT_SERIALIZATION_LIB_NAME,
    new Path("<TEXTFILE_LOCATION>")
);

HiveTap hivetap = new HiveTap(hiveTableDescriptor, 
    hiveTableDescriptor.toScheme(), SinkMode.REPLACE, false);

HiveFlow createExternalTableFlow = new HiveFlow(
    "create external",
    new String [] {
        String.format(
            "CREATE EXTERNAL TABLE IF NOT EXISTS devl_fraud.test_table ( b string, c string, a string) " +
            "ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' STORED AS TEXTFILE LOCATION '%s'",
            "<TEXTFILE_LOCATION>" ) },
    Arrays.<Tap>asList(HiveNullTap.DEV_ZERO), hivetap);

new CascadeConnector(properties).connect(createExternalTableFlow).complete();
```

I was able to create a partitioned Hive table just fine so I think my hive-site.xml configuration is correct and that I am passing it in correctly. I suspect I have something wrong with the code since I am new to cascading-hive. Any help you could provide would be much appreciated!

**Comment by fs111** [comment]
If you want to create the table w/o writing to it, you don't need a flow. You can simply call hiveTap.createResource()

**Comment by ghost** [comment]
Thanks for the advice. That simplifies the code a lot, when I took out the bits on the flow and swapped it with the createResource I got a null pointer exception:

```
Exception in thread "main" java.io.IOException: MetaException(message:java.lang.NullPointerException)
        at cascading.tap.hive.HiveTap.createHiveTable(HiveTap.java:183)
        at cascading.tap.hive.HiveTap.createResource(HiveTap.java:145)
        at com.bitwiseglobal.hive.test.WriteToPartitionedHiveTable.main(WriteToPartitionedHiveTable.java:97)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: MetaException(message:java.lang.NullPointerException)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:27002)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:26970)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result.read(ThriftHiveMetastore.java:26896)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_table_with_environment_context(ThriftHiveMetastore.java:991)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_table_with_environment_context(ThriftHiveMetastore.java:977)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.create_table_with_environment_context(HiveMetaStoreClient.java:1968)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:658)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:646)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:91)
        at com.sun.proxy.$Proxy8.createTable(Unknown Source)
        at cascading.tap.hive.HiveTap.createHiveTable(HiveTap.java:177)
        ... 8 more
```

**Comment by fs111** [comment]
can you paste the code, you are using?

**Comment by ghost** [comment]
Here is the code:

``` java
final Configuration conf = new Configuration();

conf.addResource(new Path("/etc/hive/conf/hive-site.xml"));

HiveTableDescriptor hiveTableDescriptor = new HiveTableDescriptor(
    "devl_fraud",
    "test_table",
    new String[]{"b", "c", "a"},
    new String[]{"string", "string", "string"},
    new String[]{},
    ",",
    HiveTableDescriptor.HIVE_DEFAULT_SERIALIZATION_LIB_NAME,
    new Path("/user/mvelloso/test")
);

HiveTap hivetap = new HiveTap(hiveTableDescriptor, 
    hiveTableDescriptor.toScheme(), SinkMode.REPLACE, false);

hivetap.createResource(conf);
```

**Comment by ghost** [comment]
I realized that I had forgotten to set the sentry path prefix correctly so I made some modifications to my code. Now I am trying to create an external table at _/user/mvelloso/sentry/test_. However, when I do that I witness some interesting behavior. When I print out the location of the table from the HiveTableDescriptor object I get the correct table location:

```
15/12/01 14:21:13 INFO hive.metastore: Connected to metastore.
Location: /user/mvelloso/sentry/test
```

However, when HiveTap goes to create the table it somehow gets a different URI:

```
15/12/01 14:21:19 INFO hive.metastore: Connected to metastore.
15/12/01 14:21:19 INFO hive.HiveTap: creating table 'test_table' at 'hdfs://<NAMENODE>/user/mvelloso/test' 
```

**Comment by ghost** [comment]
I fixed my issue, it turns out I was not specifying the absolute hdfs path of my external table and that is why I was getting a NullPointerException.

**Comment by fs111** [comment]
Glad you could figure it out. I am closing this issue then.
