### ISSUE TITLE
Error Reading External Table

### ISSUE THREAD

**Issue by a-rkhsib** [Cascading/cascading-hive#5]
I am trying to create a Hive tap from an external Hive:

```
    HiveTableDescriptor hiveTableDescriptor = new HiveTableDescriptor(databaseName, tableName, columnNames, columnTypes);
    // create HiveTap based on the descriptor
    HiveTap hiveTableTap = new HiveTap(hiveTableDescriptor, hiveTableDescriptor.toScheme(), REPLACE, true);
    flowDef = flowDef.addSource(currentPipe, hiveTableTap);
```

And I am getting an input path does not exist. I am using the version 1.0.0-wip-15.

A select \* from test_table works fine. The same code works also for non external table.

Any idea how to fix this?

Thanks,
Ryadh

Caused by: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: hdfs://nameservice1/user/hive/warehouse/www.db/test_table
    at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:194)
    at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:205)
    at cascading.tap.hadoop.io.MultiInputFormat.getSplits(MultiInputFormat.java:200)
    at cascading.tap.hadoop.io.MultiInputFormat.getSplits(MultiInputFormat.java:134)
    at org.apache.hadoop.mapred.JobClient.writeOldSplits(JobClient.java:1090)
    at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1082)
    at org.apache.hadoop.mapred.JobClient.access$600(JobClient.java:174)
    at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:992)
    at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:945)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1408)
    at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:945)
    at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:919)
    at cascading.flow.hadoop.planner.HadoopFlowStepJob.internalNonBlockingStart(HadoopFlowStepJob.java:105)
    at cascading.flow.planner.FlowStepJob.blockOnJob(FlowStepJob.java:196)
    at cascading.flow.planner.FlowStepJob.start(FlowStepJob.java:149)
    at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:124)
    at cascading.flow.planner.FlowStepJob.call(FlowStepJob.java:43)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)

**Comment by fs111** [comment]
That is odd. Does the table exist in the Hive metastore under the location, that is shown in the traceback? If a table already exist, we use the location found in the metastore, so if that is consistent, it should work: https://github.com/Cascading/cascading-hive/blob/wip-1.0/src/main/java/cascading/tap/hive/HiveTap.java#L354

**Comment by fs111** [comment]
No feedback for 9 month. Closing. If this is still an issue, please re-open.
